// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://roetqxwhjqaoreitzvmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJvZXRxeHdoanFhb3JlaXR6dm1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNTM0NTEsImV4cCI6MjA2MDkyOTQ1MX0.Rf8G4oh92y8BFQOTtOc_GfNuH5jrIl9mdo-zgXflPbw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);